imports:
    - { resource: parameters.yml }

debug: %debug%

databases:
    default:
        driver: %db.driver%
        hostname: %db.host%
        port: %db.port%
        username: %db.user%
        password: %db.pass%
        database: %db.name%

        charset: utf8
        collation: utf8_general_ci
        prefix: ''

auth:
    secure: %auth.secure%
    secret: %auth.secret%
    relaxed: %auth.relaxed%
    passthrough: [ /auth ]
    lifetime: %auth.lifetime%
    maxlifetime: %auth.maxlifetime%


controller.class_prefix:
controller.method_suffix: Action
controller.template_suffix: