imports:
    - { resource: parameters.yml }

debug: %debug%

databases:
    default:
        driver: %db.driver%
        hostname: %db.host%
        username: %db.user%
        password: %db.pass%
        database: %db.name%

        charset: utf8
        collation: utf8_general_ci
        prefix: ''

cookies.encrypt: true
cookies.lifetime: %cookie.lifetime%
cookies.path: /
cookies.domain:
cookies.secure: false
cookies.httponly: false
cookies.secret_key: %cookie.secret%
cookies.cookies.cipher: rijndael-256
cookies.cipher_mode: cbc

controller.class_prefix:
controller.method_suffix: Action
controller.template_suffix: