routes:

    __options:
        method: options
        path: /(:path+)
        controller: \SlimAPI\Controllers\HomeController:__options

    home:
        path: /
        controller: \SlimAPI\Controllers\HomeController:index

    login:
        method: post
        path: /auth
        controller: \SlimAPI\Controllers\AuthController:login

    product:
        method: [get, post, put, delete]
        path: /product/:id
        controller: \SlimAPI\Controllers\ProductController:get
        conditions: { id: \d+ }
